set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports even]
set_property IOSTANDARD LVCMOS33 [get_ports odd]
set_property IOSTANDARD LVCMOS33 [get_ports pause]
set_property PACKAGE_PIN R2 [get_ports even]
set_property PACKAGE_PIN R3 [get_ports odd]
set_property PACKAGE_PIN T1 [get_ports pause]
set_property PACKAGE_PIN T2 [get_ports restart]
set_property PACKAGE_PIN T3 [get_ports rst]
set_property PACKAGE_PIN U1 [get_ports terminal]
set_property IOSTANDARD LVCMOS33 [get_ports restart]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports terminal]
set_property PACKAGE_PIN U3 [get_ports {state[1]}]
set_property PACKAGE_PIN U2 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]

create_clock -period 10.000 -name my_only_clock -waveform {0.000 5.000} [get_ports clk]
set_input_delay -clock [get_clocks *] 5.000 [get_ports {pause restart}]
set_output_delay -clock [get_clocks *] 5.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]