# Constraints for ALL
set_property IOSTANDARD LVCMOS33 [get_ports *]
# Constraints for CLK
set_property PACKAGE_PIN E3 [get_ports clk]
create_clock -period 4.500 -name external_clock [get_ports clk]
# Constraints for IN*
set_property PACKAGE_PIN C2 [get_ports {in1[4]}]
set_property PACKAGE_PIN E5 [get_ports {in2[2]}]
set_property PACKAGE_PIN H5 [get_ports {in3[0]}]
set_property PACKAGE_PIN H2 [get_ports {in1[2]}]
set_property PACKAGE_PIN A3 [get_ports {in3[12]}]
set_property PACKAGE_PIN H4 [get_ports {in1[13]}]
set_property PACKAGE_PIN C6 [get_ports {in2[11]}]
set_property PACKAGE_PIN D3 [get_ports {in3[5]}]
set_property PACKAGE_PIN F4 [get_ports {in2[14]}]
set_property PACKAGE_PIN E7 [get_ports {in2[1]}]
set_property PACKAGE_PIN J5 [get_ports {in4[15]}]
set_property PACKAGE_PIN G2 [get_ports {in1[1]}]
set_property PACKAGE_PIN B1 [get_ports {in3[11]}]
set_property PACKAGE_PIN F1 [get_ports {in1[8]}]
set_property PACKAGE_PIN B6 [get_ports {in2[8]}]
set_property PACKAGE_PIN J3 [get_ports {in3[4]}]
set_property PACKAGE_PIN J4 [get_ports {in1[14]}]
set_property PACKAGE_PIN D7 [get_ports {in2[0]}]
set_property PACKAGE_PIN F3 [get_ports {in2[13]}]
set_property PACKAGE_PIN A1 [get_ports {in3[10]}]
set_property PACKAGE_PIN D2 [get_ports {in2[15]}]
set_property PACKAGE_PIN A5 [get_ports {in2[6]}]
set_property PACKAGE_PIN K2 [get_ports {in3[3]}]
set_property PACKAGE_PIN E2 [get_ports {in1[0]}]
set_property PACKAGE_PIN F6 [get_ports {in1[9]}]
set_property PACKAGE_PIN B3 [get_ports {in3[9]}]
set_property PACKAGE_PIN H1 [get_ports {in1[6]}]
set_property PACKAGE_PIN D8 [get_ports {in2[5]}]
set_property PACKAGE_PIN C1 [get_ports {in1[3]}]
set_property PACKAGE_PIN C4 [get_ports {in3[15]}]
set_property PACKAGE_PIN G4 [get_ports {in1[12]}]
set_property PACKAGE_PIN F5 [get_ports {in2[12]}]
set_property PACKAGE_PIN B2 [get_ports {in3[8]}]
set_property PACKAGE_PIN E6 [get_ports {in2[3]}]
set_property PACKAGE_PIN E1 [get_ports {in1[7]}]
set_property PACKAGE_PIN A6 [get_ports {in2[7]}]
set_property PACKAGE_PIN K1 [get_ports {in3[2]}]
set_property PACKAGE_PIN G6 [get_ports {in1[10]}]
set_property PACKAGE_PIN B4 [get_ports {in3[14]}]
set_property PACKAGE_PIN C5 [get_ports {in2[10]}]
set_property PACKAGE_PIN D5 [get_ports {in3[7]}]
set_property PACKAGE_PIN G1 [get_ports {in1[5]}]
set_property PACKAGE_PIN C7 [get_ports {in2[4]}]
set_property PACKAGE_PIN H6 [get_ports {in3[1]}]
set_property PACKAGE_PIN G3 [get_ports {in1[11]}]
set_property PACKAGE_PIN A4 [get_ports {in3[13]}]
set_property PACKAGE_PIN D4 [get_ports {in3[6]}]
set_property PACKAGE_PIN J2 [get_ports {in1[15]}]
set_property PACKAGE_PIN B7 [get_ports {in2[9]}]
set_property PACKAGE_PIN L5 [get_ports {in4[3]}]
set_property PACKAGE_PIN V2 [get_ports {in5[13]}]
set_property PACKAGE_PIN K6 [get_ports {in4[8]}]
set_property PACKAGE_PIN N5 [get_ports {in5[4]}]
set_property PACKAGE_PIN P3 [get_ports {in5[3]}]
set_property PACKAGE_PIN U2 [get_ports {in5[12]}]
set_property PACKAGE_PIN M2 [get_ports {in4[7]}]
set_property PACKAGE_PIN L1 [get_ports {in4[10]}]
set_property PACKAGE_PIN L6 [get_ports {in4[2]}]
set_property PACKAGE_PIN P2 [get_ports {in5[0]}]
set_property PACKAGE_PIN N2 [get_ports {in4[14]}]
set_property PACKAGE_PIN P4 [get_ports {in5[2]}]
set_property PACKAGE_PIN T3 [get_ports {in5[9]}]
set_property PACKAGE_PIN M3 [get_ports {in4[6]}]
set_property PACKAGE_PIN T5 [get_ports {in5[6]}]
set_property PACKAGE_PIN V1 [get_ports {in4[1]}]
set_property PACKAGE_PIN N1 [get_ports {in4[13]}]
set_property PACKAGE_PIN V5 [get_ports {in5[10]}]
set_property PACKAGE_PIN M1 [get_ports {in4[9]}]
set_property PACKAGE_PIN T4 [get_ports {in5[7]}]
set_property PACKAGE_PIN U1 [get_ports {in4[0]}]
set_property PACKAGE_PIN K3 [get_ports {in4[12]}]
set_property PACKAGE_PIN R2 [get_ports {in5[1]}]
set_property PACKAGE_PIN L4 [get_ports {in4[5]}]
set_property PACKAGE_PIN P5 [get_ports {in5[5]}]
set_property PACKAGE_PIN U3 [get_ports {in5[15]}]
set_property PACKAGE_PIN L3 [get_ports {in4[11]}]
set_property PACKAGE_PIN V4 [get_ports {in5[11]}]
set_property PACKAGE_PIN K5 [get_ports {in4[4]}]
set_property PACKAGE_PIN U4 [get_ports {in5[14]}]
set_property PACKAGE_PIN R3 [get_ports {in5[8]}]
# Constraints for OUT*
set_property PACKAGE_PIN G13 [get_ports {out2[10]}]
set_property PACKAGE_PIN H17 [get_ports {out3[11]}]
set_property PACKAGE_PIN E16 [get_ports {out1[15]}]
set_property PACKAGE_PIN H16 [get_ports {out2[5]}]
set_property PACKAGE_PIN C17 [get_ports {out3[8]}]
set_property PACKAGE_PIN G16 [get_ports {out2[6]}]
set_property PACKAGE_PIN F16 [get_ports {out2[4]}]
set_property PACKAGE_PIN C12 [get_ports {out1[0]}]
set_property PACKAGE_PIN J14 [get_ports {out3[9]}]
set_property PACKAGE_PIN K16 [get_ports {out4[14]}]
set_property PACKAGE_PIN E17 [get_ports {out3[15]}]
set_property PACKAGE_PIN G18 [get_ports {out3[3]}]
set_property PACKAGE_PIN G17 [get_ports {out3[12]}]
set_property PACKAGE_PIN F13 [get_ports {out1[4]}]
set_property PACKAGE_PIN K15 [get_ports {out4[15]}]
set_property PACKAGE_PIN D14 [get_ports {out2[12]}]
set_property PACKAGE_PIN B17 [get_ports {out1[7]}]
set_property PACKAGE_PIN F18 [get_ports {out3[4]}]
set_property PACKAGE_PIN D13 [get_ports {out1[5]}]
set_property PACKAGE_PIN C14 [get_ports {out2[11]}]
set_property PACKAGE_PIN B18 [get_ports {out1[14]}]
set_property PACKAGE_PIN B12 [get_ports {out2[15]}]
set_property PACKAGE_PIN H15 [get_ports {out3[10]}]
set_property PACKAGE_PIN J13 [get_ports {out3[14]}]
set_property PACKAGE_PIN B14 [get_ports {out2[13]}]
set_property PACKAGE_PIN A15 [get_ports {out1[10]}]
set_property PACKAGE_PIN E18 [get_ports {out3[5]}]
set_property PACKAGE_PIN D12 [get_ports {out1[6]}]
set_property PACKAGE_PIN A13 [get_ports {out1[12]}]
set_property PACKAGE_PIN E15 [get_ports {out2[9]}]
set_property PACKAGE_PIN A11 [get_ports {out1[1]}]
set_property PACKAGE_PIN D17 [get_ports {out2[0]}]
set_property PACKAGE_PIN B11 [get_ports {out1[2]}]
set_property PACKAGE_PIN J15 [get_ports {out3[0]}]
set_property PACKAGE_PIN F14 [get_ports {out1[3]}]
set_property PACKAGE_PIN B16 [get_ports {out1[8]}]
set_property PACKAGE_PIN B13 [get_ports {out2[14]}]
set_property PACKAGE_PIN A16 [get_ports {out1[9]}]
set_property PACKAGE_PIN D18 [get_ports {out3[6]}]
set_property PACKAGE_PIN G14 [get_ports {out2[2]}]
set_property PACKAGE_PIN K13 [get_ports {out3[13]}]
set_property PACKAGE_PIN J17 [get_ports {out3[1]}]
set_property PACKAGE_PIN D15 [get_ports {out2[7]}]
set_property PACKAGE_PIN H14 [get_ports {out2[1]}]
set_property PACKAGE_PIN A14 [get_ports {out1[11]}]
set_property PACKAGE_PIN C16 [get_ports {out3[7]}]
set_property PACKAGE_PIN F15 [get_ports {out2[3]}]
set_property PACKAGE_PIN A18 [get_ports {out1[13]}]
set_property PACKAGE_PIN C15 [get_ports {out2[8]}]
set_property PACKAGE_PIN J18 [get_ports {out3[2]}]
set_property PACKAGE_PIN R17 [get_ports {out5[6]}]
set_property PACKAGE_PIN R11 [get_ports {out4[7]}]
set_property PACKAGE_PIN P18 [get_ports {out5[12]}]
set_property PACKAGE_PIN L15 [get_ports {out4[13]}]
set_property PACKAGE_PIN T14 [get_ports {out5[1]}]
set_property PACKAGE_PIN M13 [get_ports {out4[2]}]
set_property PACKAGE_PIN N15 [get_ports {out5[7]}]
set_property PACKAGE_PIN N14 [get_ports {out5[13]}]
set_property PACKAGE_PIN T15 [get_ports {out5[2]}]
set_property PACKAGE_PIN N16 [get_ports {out5[8]}]
set_property PACKAGE_PIN K18 [get_ports {out4[8]}]
set_property PACKAGE_PIN P14 [get_ports {out5[14]}]
set_property PACKAGE_PIN R12 [get_ports {out4[3]}]
set_property PACKAGE_PIN M16 [get_ports {out5[9]}]
set_property PACKAGE_PIN K17 [get_ports {out4[9]}]
set_property PACKAGE_PIN R18 [get_ports {out5[15]}]
set_property PACKAGE_PIN P15 [get_ports {out5[3]}]
set_property PACKAGE_PIN R13 [get_ports {out4[4]}]
set_property PACKAGE_PIN M17 [get_ports {out5[10]}]
set_property PACKAGE_PIN M14 [get_ports {out4[10]}]
set_property PACKAGE_PIN R15 [get_ports {out5[4]}]
set_property PACKAGE_PIN L18 [get_ports {out4[5]}]
set_property PACKAGE_PIN L14 [get_ports {out4[11]}]
set_property PACKAGE_PIN T18 [get_ports {out4[0]}]
set_property PACKAGE_PIN P17 [get_ports {out5[5]}]
set_property PACKAGE_PIN M18 [get_ports {out4[6]}]
set_property PACKAGE_PIN N17 [get_ports {out5[11]}]
set_property PACKAGE_PIN L16 [get_ports {out4[12]}]
set_property PACKAGE_PIN T16 [get_ports {out5[0]}]
set_property PACKAGE_PIN L13 [get_ports {out4[1]}]
# Constraints for CFGBVS
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

create_pblock pblock_5
add_cells_to_pblock [get_pblocks pblock_5] [get_cells -quiet [list s5_1n2 s5_3n4 s5_5]]
resize_pblock [get_pblocks pblock_5] -add {SLICE_X46Y50:SLICE_X47Y74}
create_pblock pblock_4
add_cells_to_pblock [get_pblocks pblock_4] [get_cells -quiet [list s4_1 s4_2n3 s4_4n5]]
resize_pblock [get_pblocks pblock_4] -add {SLICE_X44Y50:SLICE_X45Y74}
create_pblock pblock_3
add_cells_to_pblock [get_pblocks pblock_3] [get_cells -quiet [list s3_1n2 s3_3n4 s3_5]]
resize_pblock [get_pblocks pblock_3] -add {SLICE_X42Y50:SLICE_X43Y74}
create_pblock pblock_2
add_cells_to_pblock [get_pblocks pblock_2] [get_cells -quiet [list s2_1 s2_2n3 s2_4n5]]
resize_pblock [get_pblocks pblock_2] -add {SLICE_X40Y50:SLICE_X41Y74}
create_pblock pblock_1
add_cells_to_pblock [get_pblocks pblock_1] [get_cells -quiet [list s1_1n2 s1_3n4 s1_5]]
resize_pblock [get_pblocks pblock_1] -add {SLICE_X38Y50:SLICE_X39Y74}
create_pblock pblock_0
add_cells_to_pblock [get_pblocks pblock_0] [get_cells -quiet [list s0_1 s0_2 s0_3 s0_4 s0_5]]
resize_pblock [get_pblocks pblock_0] -add {SLICE_X36Y50:SLICE_X37Y74}
